// <auto-generated />
using System;
using CRM.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRM.Migrations
{
    [DbContext(typeof(CrmDbContext))]
    [Migration("20240823022708_AddIsActiveInNguoiDung")]
    partial class AddIsActiveInNguoiDung
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CRM.Entities.ChucVu", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenChucVu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_ChucVu");

                    b.ToTable("ChucVu", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.Nguoidung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HoVaDem")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("MaChucVu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MaPhongBan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("MaTinhTrang")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgayBatDauLamViec")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayThuViec")
                        .HasColumnType("datetime");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("TaiKhoan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_NguoiDung");

                    b.HasIndex("MaChucVu");

                    b.HasIndex("MaPhongBan");

                    b.HasIndex("MaTinhTrang");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.PhongBan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenPhongBan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_PhongBan");

                    b.ToTable("PhongBan", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.TinhTrang", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("TenTinhTrang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_TinhTrang");

                    b.ToTable("TinhTrang", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.Nguoidung", b =>
                {
                    b.HasOne("CRM.Entities.ChucVu", "ChucVu")
                        .WithMany("Nguoidung")
                        .HasForeignKey("MaChucVu")
                        .HasConstraintName("FK_ChucVu_NguoiDung");

                    b.HasOne("CRM.Entities.PhongBan", "PhongBan")
                        .WithMany("Nguoidung")
                        .HasForeignKey("MaPhongBan")
                        .HasConstraintName("FK_PhongBan_NguoiDung");

                    b.HasOne("CRM.Entities.TinhTrang", "TinhTrang")
                        .WithMany("Nguoidung")
                        .HasForeignKey("MaTinhTrang")
                        .HasConstraintName("FK_TinhTrang_NguoiDung");

                    b.Navigation("ChucVu");

                    b.Navigation("PhongBan");

                    b.Navigation("TinhTrang");
                });

            modelBuilder.Entity("CRM.Entities.ChucVu", b =>
                {
                    b.Navigation("Nguoidung");
                });

            modelBuilder.Entity("CRM.Entities.PhongBan", b =>
                {
                    b.Navigation("Nguoidung");
                });

            modelBuilder.Entity("CRM.Entities.TinhTrang", b =>
                {
                    b.Navigation("Nguoidung");
                });
#pragma warning restore 612, 618
        }
    }
}
