// <auto-generated />
using System;
using CRM.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRM.Migrations
{
    [DbContext(typeof(CrmDbContext))]
    partial class CrmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CRM.Entities.BaoGia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaCoHoi")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaKhachHang")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaSoThue")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaTinhTrangBaoGia")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("NgayBaoGia")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayHetHan")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("NguoiDungId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PhongBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenBaoGia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal");

                    b.HasKey("Id")
                        .HasName("PK_BaoGia");

                    b.HasIndex("MaCoHoi");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaTinhTrangBaoGia");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("PhongBanId");

                    b.ToTable("BaoGia", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.ChiTietKetQua", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaCoHoi")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("MaGiaiDoan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("MaLyDo")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayKyVongKetThuc")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("SoTien")
                        .HasColumnType("decimal");

                    b.HasKey("Id")
                        .HasName("PK_ChiTietKetQua");

                    b.HasIndex("MaCoHoi")
                        .IsUnique()
                        .HasFilter("[MaCoHoi] IS NOT NULL");

                    b.HasIndex("MaGiaiDoan");

                    b.HasIndex("MaLyDo");

                    b.ToTable("ChiTietKetQua", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.ChucVu", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TenChucVu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_ChucVu");

                    b.ToTable("ChucVu", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.CoHoi", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal?>("DoanhSoKyVong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("MaGiaiDoanBanHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaKhachHang")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaLienHe")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("MaLoaiCoHoi")
                        .HasColumnType("int");

                    b.Property<int?>("MaLoaiHangHoa")
                        .HasColumnType("int");

                    b.Property<int?>("MaNguonGocKhachHang")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayKyVongKetThuc")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("NguoiDungId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PhongBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("SoTien")
                        .HasColumnType("decimal");

                    b.Property<string>("TenCoHoi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TiLeThanhCong")
                        .HasColumnType("interger");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK_CoHoi");

                    b.HasIndex("MaGiaiDoanBanHang");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaLienHe");

                    b.HasIndex("MaLoaiCoHoi");

                    b.HasIndex("MaLoaiHangHoa");

                    b.HasIndex("MaNguonGocKhachHang");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("PhongBanId");

                    b.ToTable("CoHoi", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.CuocGoi", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoHoiId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsHoanThanh")
                        .HasColumnType("bit");

                    b.Property<Guid?>("KetQuaCuocGoiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("KhachHangMucTieuId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("KhachHangTiemNangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LoaiCuocGoiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("NguoiDungId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PhongBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("SoGiayGoi")
                        .HasColumnType("int");

                    b.Property<int?>("SoPhutGoi")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_CuocGoi");

                    b.HasIndex("CoHoiId");

                    b.HasIndex("KetQuaCuocGoiId");

                    b.HasIndex("KhachHangMucTieuId");

                    b.HasIndex("KhachHangTiemNangId");

                    b.HasIndex("LoaiCuocGoiId");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("PhongBanId");

                    b.ToTable("CuocGoi", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.DoanhThu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenDoanhThu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_DoanhThu");

                    b.ToTable("DoanhThu", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.DonHang", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime");

                    b.Property<decimal>("GiaTriDonHang")
                        .HasColumnType("decimal");

                    b.Property<DateTime?>("HanGiaoHang")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("HanThanhToan")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGhiDoanhSo")
                        .HasColumnType("bit");

                    b.Property<string>("MaBaoGia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaKhachHang")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaLienHe")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaLoaiDonHang")
                        .HasColumnType("int");

                    b.Property<string>("MaQuanLy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaTinhTrangDonHang")
                        .HasColumnType("int");

                    b.Property<int?>("MaTinhTrangGhiDoanhSo")
                        .HasColumnType("int");

                    b.Property<string>("MoTaDonHang")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("NgayDatHang")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayGhiDoanhSo")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("NguoiDungId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PhongBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SoTienConPhaiThu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenDonHang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ThongTinGiaoHang")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ThongTinHoaDon")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("ThucThuDonHang")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id")
                        .HasName("PK_DonHang");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaLienHe");

                    b.HasIndex("MaLoaiDonHang");

                    b.HasIndex("MaTinhTrangDonHang");

                    b.HasIndex("MaTinhTrangGhiDoanhSo");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("PhongBanId");

                    b.ToTable("DonHang", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.DonViTinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TiLeChuyenDoi")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_DonViTinh");

                    b.ToTable("DonViTinh", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.EmailDaGui", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiaChiGui")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DiaChiNhan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("KhachHangMucTieuId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("KhachHangTiemNangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NguoiDungId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PhongBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TieuDe")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_EmailDaGui");

                    b.HasIndex("KhachHangMucTieuId");

                    b.HasIndex("KhachHangTiemNangId");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("PhongBanId");

                    b.ToTable("EmailDaGui", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.GiaiDoanBanHang", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("MaLoaiDuBao")
                        .HasColumnType("int");

                    b.Property<int?>("MaPhanLoaiDuBao")
                        .HasColumnType("int");

                    b.Property<int?>("Stt")
                        .HasColumnType("int");

                    b.Property<string>("TenGiaiDoan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TiLeThanhCong")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_GiaiDoanBanHang");

                    b.HasIndex("MaLoaiDuBao");

                    b.HasIndex("MaPhanLoaiDuBao");

                    b.ToTable("GiaiDoanBanhang", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.HangHoa", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal");

                    b.Property<string>("DuongDanHinhAnh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaDonViTinh")
                        .HasColumnType("int");

                    b.Property<int>("MaLoaiHangHoa")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NguonGoc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("integer");

                    b.Property<string>("TenHangHoa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_HangHoaId");

                    b.HasIndex("MaDonViTinh");

                    b.HasIndex("MaLoaiHangHoa");

                    b.ToTable("HangHoa", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.HangHoaQuanTam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BaoGiaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ChiecKhauDonHang")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CoHoiId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal");

                    b.Property<string>("HoaDonId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KhachHangId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("KhachHangTiemNangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaHangHoaId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenHangHoa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal");

                    b.Property<int?>("ThueSuat")
                        .HasColumnType("int");

                    b.Property<decimal?>("TienThue")
                        .HasColumnType("decimal");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal");

                    b.HasKey("Id")
                        .HasName("PK_HangHoaQuanTam");

                    b.HasIndex("MaHangHoaId");

                    b.ToTable("HangHoaQuanTam", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.KetQuaCuocGoi", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_KetQuaCuocGoi");

                    b.ToTable("KetQuaCuocGoi", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.KhachHangMucTieu", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDungChung")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsKhachHangCaNhan")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsNhaPhanPhoi")
                        .HasColumnType("bit");

                    b.Property<int?>("MaDoanhThu")
                        .HasColumnType("int");

                    b.Property<int?>("MaLinhVuc")
                        .HasColumnType("int");

                    b.Property<int?>("MaLoaiHinhNgheNghiep")
                        .HasColumnType("int");

                    b.Property<int?>("MaLoaiTiemNang")
                        .HasColumnType("int");

                    b.Property<int?>("MaNganhNghe")
                        .HasColumnType("int");

                    b.Property<int?>("MaNguonGocKhachHang")
                        .HasColumnType("int");

                    b.Property<int?>("MaPhongbanKhachHang")
                        .HasColumnType("int");

                    b.Property<string>("MaSoThue")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgayThanhLap")
                        .HasColumnType("date");

                    b.Property<Guid?>("NguoiDungId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PhongBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TaiKhoanNganHang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenKhachHang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenVietTat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ThongTinGiaoHang")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ThongTinHoaDon")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Website")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_KhachHangMucTieu");

                    b.HasIndex("MaDoanhThu");

                    b.HasIndex("MaLinhVuc");

                    b.HasIndex("MaLoaiHinhNgheNghiep");

                    b.HasIndex("MaLoaiTiemNang");

                    b.HasIndex("MaNganhNghe");

                    b.HasIndex("MaNguonGocKhachHang");

                    b.HasIndex("MaPhongbanKhachHang");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("PhongBanId");

                    b.ToTable("KhachHangMucTieu", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.KhachHangTiemNang", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChucDanh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmailCaNhan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmailCoQuan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsChuyenDoi")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDungChung")
                        .HasColumnType("bit");

                    b.Property<int?>("MaDoanhThu")
                        .HasColumnType("int");

                    b.Property<int?>("MaLinhVuc")
                        .HasColumnType("int");

                    b.Property<int?>("MaLoaiHinhNgheNghiep")
                        .HasColumnType("int");

                    b.Property<int?>("MaLoaiTiemNang")
                        .HasColumnType("int");

                    b.Property<int?>("MaNganhNghe")
                        .HasColumnType("int");

                    b.Property<int?>("MaNguonGocKhachHang")
                        .HasColumnType("int");

                    b.Property<int?>("MaPhongbanKhachHang")
                        .HasColumnType("int");

                    b.Property<string>("MaSoThue")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("NgayThanhLap")
                        .HasColumnType("date");

                    b.Property<Guid?>("NguoiDungId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PhongBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SoDienThoaiCoQuan")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("SoDienThoaiDiDong")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("SoZalo")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("TenKhachHang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenToChuc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ThongTinMoTa")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK_KhachHangTiemNang");

                    b.HasIndex("MaDoanhThu");

                    b.HasIndex("MaLinhVuc");

                    b.HasIndex("MaLoaiHinhNgheNghiep");

                    b.HasIndex("MaLoaiTiemNang");

                    b.HasIndex("MaNganhNghe");

                    b.HasIndex("MaNguonGocKhachHang");

                    b.HasIndex("MaPhongbanKhachHang");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("PhongBanId");

                    b.ToTable("KhachHangTiemNang", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.LichHen", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoHoiId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime");

                    b.Property<string>("DiaDiem")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("KhachHangMucTieuId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("KhachHangTiemNangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<Guid?>("NguoiDungId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PhongBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TieuDe")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("TrangThaiThucHienId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_LichHen");

                    b.HasIndex("CoHoiId");

                    b.HasIndex("KhachHangMucTieuId");

                    b.HasIndex("KhachHangTiemNangId");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("PhongBanId");

                    b.HasIndex("TrangThaiThucHienId");

                    b.ToTable("LichHen", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.LienHe", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("KhachHangId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("KhachHangTiemNangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NguoiDungId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PhongBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("TenLienHe")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("XungHo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_LienHe");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("PhongBanId");

                    b.ToTable("LienHe", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.LinhVucNgheNghiep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenLinhVuc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_LinhVucNgheNghiep");

                    b.ToTable("LinhVucNgheNghiep", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.LoaiCoHoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_LoaiCoHoi");

                    b.ToTable("LoaiCoHoi", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.LoaiCuocGoi", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenCuocGoi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_LoaiCuocGoi");

                    b.ToTable("LoaiCuocGoi", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.LoaiDonHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_LoaiDonhang");

                    b.ToTable("LoaiDonHang", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.LoaiDuBao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_LoaiDuBao");

                    b.ToTable("LoaiDuBao", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.LoaiHangHoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("LoaiHangHoaId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_LoaiHangHoa");

                    b.HasIndex("LoaiHangHoaId");

                    b.ToTable("LoaiHangHoa", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.LoaiHinhNgheNghiep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenLoaiHinh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_LoaiHinhNgheNghiep");

                    b.ToTable("LoaiHinhNgheNghiep", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.LoaiTiemNang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenLoaiTiemNang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_LoaiTiemNang");

                    b.ToTable("LoaiTiemNang", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.LyDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_LyDo");

                    b.ToTable("LyDo", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_menu");

                    b.ToTable("Menu", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.MenuRole", b =>
                {
                    b.Property<Guid>("MenuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Sua")
                        .HasColumnType("bit");

                    b.Property<bool?>("Them")
                        .HasColumnType("bit");

                    b.Property<bool?>("Xem")
                        .HasColumnType("bit");

                    b.Property<bool?>("Xoa")
                        .HasColumnType("bit");

                    b.HasKey("MenuId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("Menu_Group", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.MucDoUuTien", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_MucDoUuTien");

                    b.ToTable("MucDoUuTien", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.NganhNghe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaLinhVucNgheNghiep")
                        .HasColumnType("int");

                    b.Property<string>("TenNganhNghe")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_NganhNghe");

                    b.HasIndex("MaLinhVucNgheNghiep");

                    b.ToTable("NganhNghe", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.Nguoidung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CheckIsGiamDoc")
                        .HasColumnType("bit");

                    b.Property<bool>("CheckIsTruongPhong")
                        .HasColumnType("bit");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("DoanhSoDuKien")
                        .HasMaxLength(50)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DoanhSoThucTe")
                        .HasMaxLength(50)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("HinhAnh")
                        .HasColumnType("varbinary(MAX)");

                    b.Property<string>("HoVaDem")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("MaChucVu")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MaPhongBan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("MaTinhTrang")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgayBatDauLamViec")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayThuViec")
                        .HasColumnType("datetime");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("TaiKhoan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_NguoiDung");

                    b.HasIndex("MaChucVu");

                    b.HasIndex("MaPhongBan");

                    b.HasIndex("MaTinhTrang");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.NguonGocKhachHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenNguonGoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_NguonGocKhachHang");

                    b.ToTable("NguonGocKhachHang", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.NhiemVu", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoHoiId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HanHoanThanh")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsThongBao")
                        .HasColumnType("bit");

                    b.Property<string>("KhachHangMucTieuId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("KhachHangTiemNangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid?>("MucDoUuTienId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NguoiDungId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PhongBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TieuDe")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("TrangThaiThucHienId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_NhiemVu");

                    b.HasIndex("CoHoiId");

                    b.HasIndex("KhachHangMucTieuId");

                    b.HasIndex("KhachHangTiemNangId");

                    b.HasIndex("MucDoUuTienId");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("PhongBanId");

                    b.HasIndex("TrangThaiThucHienId");

                    b.ToTable("NhiemVu", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.PhanLoaiDuBao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_PhanLoaiDuBao");

                    b.ToTable("PhanLoaiDuBao", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.PhongBan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MaQuanLy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoThuTu")
                        .HasColumnType("int");

                    b.Property<string>("TenPhongBan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_PhongBan");

                    b.ToTable("PhongBan", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.PhongBanKhachHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenPhongban")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_PhongBanKhachhang");

                    b.ToTable("PhongBanKhachHang", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.ThongBao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime");

                    b.Property<string>("DuongDan")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsRead")
                        .HasColumnType("bit");

                    b.Property<Guid?>("NguoiDungId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TieuDe")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id")
                        .HasName("PK_ThongBao");

                    b.ToTable("ThongBao", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.TinhTrang", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("TenTinhTrang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_TinhTrang");

                    b.ToTable("TinhTrang", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.TinhTrangBaoGia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_TinhTrangBaoGia");

                    b.ToTable("TinhTrangBaoGia", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.TinhTrangDonHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_TinhTrangDonHang");

                    b.ToTable("TinhTrangDonHang", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.TinhTrangGhiDoanhSo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_TinhTrangGhiDoanhSo");

                    b.ToTable("TinhTrangGhiDoanhSo", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.TrangThaiThucHien", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_TrangThaiThucHien");

                    b.ToTable("TrangThaiThucHien", (string)null);
                });

            modelBuilder.Entity("CRM.Entities.BaoGia", b =>
                {
                    b.HasOne("CRM.Entities.CoHoi", "CoHoi")
                        .WithMany("BaoGias")
                        .HasForeignKey("MaCoHoi")
                        .HasConstraintName("FK_CoHoi_BaoGia");

                    b.HasOne("CRM.Entities.KhachHangMucTieu", "KhachHangMucTieu")
                        .WithMany("BaoGias")
                        .HasForeignKey("MaKhachHang")
                        .HasConstraintName("FK_KhachHang_BaoGia");

                    b.HasOne("CRM.Entities.TinhTrangBaoGia", "TinhTrangBaoGia")
                        .WithMany("BaoGias")
                        .HasForeignKey("MaTinhTrangBaoGia")
                        .HasConstraintName("FK_TinhTrangBaoGia_BaoGia");

                    b.HasOne("CRM.Entities.Nguoidung", "Nguoidung")
                        .WithMany("BaoGias")
                        .HasForeignKey("NguoiDungId")
                        .HasConstraintName("FK_NguoiDung_BaoGia");

                    b.HasOne("CRM.Entities.PhongBan", "PhongBan")
                        .WithMany("BaoGias")
                        .HasForeignKey("PhongBanId")
                        .HasConstraintName("FK_PhongBan_BaoGia");

                    b.Navigation("CoHoi");

                    b.Navigation("KhachHangMucTieu");

                    b.Navigation("Nguoidung");

                    b.Navigation("PhongBan");

                    b.Navigation("TinhTrangBaoGia");
                });

            modelBuilder.Entity("CRM.Entities.ChiTietKetQua", b =>
                {
                    b.HasOne("CRM.Entities.CoHoi", "CoHoi")
                        .WithOne("ChiTietKetQua")
                        .HasForeignKey("CRM.Entities.ChiTietKetQua", "MaCoHoi")
                        .HasConstraintName("FK_CoHoi_ChiTietKetQua");

                    b.HasOne("CRM.Entities.GiaiDoanBanHang", "GiaiDoanBanHang")
                        .WithMany("ChiTietKetQuas")
                        .HasForeignKey("MaGiaiDoan")
                        .HasConstraintName("FK_GiaiDoanBanHang_ChiTietKetQua");

                    b.HasOne("CRM.Entities.LyDo", "LyDo")
                        .WithMany("ChiTietKetQuas")
                        .HasForeignKey("MaLyDo")
                        .HasConstraintName("FK_LyDo_ChiTietKetQua");

                    b.Navigation("CoHoi");

                    b.Navigation("GiaiDoanBanHang");

                    b.Navigation("LyDo");
                });

            modelBuilder.Entity("CRM.Entities.CoHoi", b =>
                {
                    b.HasOne("CRM.Entities.GiaiDoanBanHang", "GiaiDoanBanHang")
                        .WithMany("CoHois")
                        .HasForeignKey("MaGiaiDoanBanHang")
                        .HasConstraintName("FK_GiaiDoanBanHang_CoHoi");

                    b.HasOne("CRM.Entities.KhachHangMucTieu", "KhachHangMucTieu")
                        .WithMany("CoHois")
                        .HasForeignKey("MaKhachHang")
                        .HasConstraintName("FK_KhachHangMucTieu_CoHoi");

                    b.HasOne("CRM.Entities.LienHe", "LienHe")
                        .WithMany("CoHois")
                        .HasForeignKey("MaLienHe")
                        .HasConstraintName("FK_LienHe_CoHoi");

                    b.HasOne("CRM.Entities.LoaiCoHoi", "LoaiCoHoi")
                        .WithMany("CoHois")
                        .HasForeignKey("MaLoaiCoHoi")
                        .HasConstraintName("FK_LoaiCoHoi_CoHoi");

                    b.HasOne("CRM.Entities.LoaiHangHoa", "LoaiHangHoa")
                        .WithMany("CoHois")
                        .HasForeignKey("MaLoaiHangHoa")
                        .HasConstraintName("FK_LoaiHangHoa_CoHoi");

                    b.HasOne("CRM.Entities.NguonGocKhachHang", "NguonGocKhachHang")
                        .WithMany("CoHois")
                        .HasForeignKey("MaNguonGocKhachHang")
                        .HasConstraintName("FK_NguonGocKhachHang_CoHoi");

                    b.HasOne("CRM.Entities.Nguoidung", "Nguoidung")
                        .WithMany("CoHois")
                        .HasForeignKey("NguoiDungId")
                        .HasConstraintName("FK_NguoiDung_CoHoi");

                    b.HasOne("CRM.Entities.PhongBan", "PhongBan")
                        .WithMany("CoHois")
                        .HasForeignKey("PhongBanId")
                        .HasConstraintName("FK_PhongBan_CoHoi");

                    b.Navigation("GiaiDoanBanHang");

                    b.Navigation("KhachHangMucTieu");

                    b.Navigation("LienHe");

                    b.Navigation("LoaiCoHoi");

                    b.Navigation("LoaiHangHoa");

                    b.Navigation("Nguoidung");

                    b.Navigation("NguonGocKhachHang");

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("CRM.Entities.CuocGoi", b =>
                {
                    b.HasOne("CRM.Entities.CoHoi", "CoHoi")
                        .WithMany("CuocGois")
                        .HasForeignKey("CoHoiId")
                        .HasConstraintName("FK_CoHoi_CuocGoi");

                    b.HasOne("CRM.Entities.KetQuaCuocGoi", "KetQuaCuocGoi")
                        .WithMany("CuocGois")
                        .HasForeignKey("KetQuaCuocGoiId")
                        .HasConstraintName("FK_KetQuaCuocGoi_CuocGoi");

                    b.HasOne("CRM.Entities.KhachHangMucTieu", "KhachHangMucTieu")
                        .WithMany("CuocGois")
                        .HasForeignKey("KhachHangMucTieuId")
                        .HasConstraintName("FK_KHMucTieu_CuocGoi");

                    b.HasOne("CRM.Entities.KhachHangTiemNang", "KhachHangTiemNang")
                        .WithMany("CuocGois")
                        .HasForeignKey("KhachHangTiemNangId")
                        .HasConstraintName("FK_KHTiemNang_CuocGoi");

                    b.HasOne("CRM.Entities.LoaiCuocGoi", "LoaiCuocGoi")
                        .WithMany("CuocGois")
                        .HasForeignKey("LoaiCuocGoiId")
                        .HasConstraintName("FK_LoaiCuocGoi_CuocGoi");

                    b.HasOne("CRM.Entities.Nguoidung", "Nguoidung")
                        .WithMany("CuocGois")
                        .HasForeignKey("NguoiDungId")
                        .HasConstraintName("FK_NguoiDung_CuocGoi");

                    b.HasOne("CRM.Entities.PhongBan", "PhongBan")
                        .WithMany("CuocGois")
                        .HasForeignKey("PhongBanId")
                        .HasConstraintName("FK_PhongBan_CuocGoi");

                    b.Navigation("CoHoi");

                    b.Navigation("KetQuaCuocGoi");

                    b.Navigation("KhachHangMucTieu");

                    b.Navigation("KhachHangTiemNang");

                    b.Navigation("LoaiCuocGoi");

                    b.Navigation("Nguoidung");

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("CRM.Entities.DonHang", b =>
                {
                    b.HasOne("CRM.Entities.KhachHangMucTieu", "KhachHangMucTieu")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaKhachHang")
                        .HasConstraintName("FK_KhachHangMucTieu_DonHang");

                    b.HasOne("CRM.Entities.LienHe", "LienHe")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaLienHe")
                        .HasConstraintName("FK_LienHe_DonHang");

                    b.HasOne("CRM.Entities.LoaiDonHang", "LoaiDonHang")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaLoaiDonHang")
                        .IsRequired()
                        .HasConstraintName("FK_LoaiDonHang_DonHang");

                    b.HasOne("CRM.Entities.TinhTrangDonHang", "TinhTrangDonHang")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaTinhTrangDonHang")
                        .HasConstraintName("FK_TinhTrangDonHang_DonHang");

                    b.HasOne("CRM.Entities.TinhTrangGhiDoanhSo", "TinhTrangGhiDoanhSo")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaTinhTrangGhiDoanhSo")
                        .HasConstraintName("FK_TinhTrangGhiDoanhSo_DonHang");

                    b.HasOne("CRM.Entities.Nguoidung", "Nguoidung")
                        .WithMany("DonHangs")
                        .HasForeignKey("NguoiDungId")
                        .HasConstraintName("FK_NguoiDung_DonHang");

                    b.HasOne("CRM.Entities.PhongBan", "PhongBan")
                        .WithMany("DonHangs")
                        .HasForeignKey("PhongBanId")
                        .HasConstraintName("FK_PhongBan_DonHang");

                    b.Navigation("KhachHangMucTieu");

                    b.Navigation("LienHe");

                    b.Navigation("LoaiDonHang");

                    b.Navigation("Nguoidung");

                    b.Navigation("PhongBan");

                    b.Navigation("TinhTrangDonHang");

                    b.Navigation("TinhTrangGhiDoanhSo");
                });

            modelBuilder.Entity("CRM.Entities.EmailDaGui", b =>
                {
                    b.HasOne("CRM.Entities.KhachHangMucTieu", "KhachHangMucTieu")
                        .WithMany("EmailDaGuis")
                        .HasForeignKey("KhachHangMucTieuId")
                        .HasConstraintName("FK_KhachHangMucTieu_EmailDaGui");

                    b.HasOne("CRM.Entities.KhachHangTiemNang", "KhachHangTiemNang")
                        .WithMany("EmailDaGuis")
                        .HasForeignKey("KhachHangTiemNangId")
                        .HasConstraintName("FK_KhachHangTiemNang_EmailDaGui");

                    b.HasOne("CRM.Entities.Nguoidung", "Nguoidung")
                        .WithMany("EmailDaGuis")
                        .HasForeignKey("NguoiDungId")
                        .HasConstraintName("FK_NguoiDung_EmailDaGui");

                    b.HasOne("CRM.Entities.PhongBan", "PhongBan")
                        .WithMany("EmailDaGuis")
                        .HasForeignKey("PhongBanId")
                        .HasConstraintName("FK_PhongBan_EmailDaGui");

                    b.Navigation("KhachHangMucTieu");

                    b.Navigation("KhachHangTiemNang");

                    b.Navigation("Nguoidung");

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("CRM.Entities.GiaiDoanBanHang", b =>
                {
                    b.HasOne("CRM.Entities.LoaiDuBao", "LoaiDuBao")
                        .WithMany("GiaiDoanBanHangs")
                        .HasForeignKey("MaLoaiDuBao")
                        .HasConstraintName("FK_LoaiDuBao_GiaiDoanBanHang");

                    b.HasOne("CRM.Entities.PhanLoaiDuBao", "PhanLoaiDuBao")
                        .WithMany("GiaiDoanBanHangs")
                        .HasForeignKey("MaPhanLoaiDuBao")
                        .HasConstraintName("FK_PhanLoaiDuBao_GiaiDoanBanHang");

                    b.Navigation("LoaiDuBao");

                    b.Navigation("PhanLoaiDuBao");
                });

            modelBuilder.Entity("CRM.Entities.HangHoa", b =>
                {
                    b.HasOne("CRM.Entities.DonViTinh", "DonViTinh")
                        .WithMany("HangHoas")
                        .HasForeignKey("MaDonViTinh")
                        .IsRequired()
                        .HasConstraintName("FK_DonViTinh_HangHoa");

                    b.HasOne("CRM.Entities.LoaiHangHoa", "LoaiHangHoa")
                        .WithMany("HangHoas")
                        .HasForeignKey("MaLoaiHangHoa")
                        .IsRequired()
                        .HasConstraintName("FK_LoaiHangHoa_HangHoa");

                    b.Navigation("DonViTinh");

                    b.Navigation("LoaiHangHoa");
                });

            modelBuilder.Entity("CRM.Entities.HangHoaQuanTam", b =>
                {
                    b.HasOne("CRM.Entities.HangHoa", "HangHoa")
                        .WithMany("HangHoaQuanTams")
                        .HasForeignKey("MaHangHoaId")
                        .HasConstraintName("FK_HangHoa_HangHoaQuanTam");

                    b.Navigation("HangHoa");
                });

            modelBuilder.Entity("CRM.Entities.KhachHangMucTieu", b =>
                {
                    b.HasOne("CRM.Entities.DoanhThu", "DoanhThu")
                        .WithMany("KhachHangMucTieus")
                        .HasForeignKey("MaDoanhThu")
                        .HasConstraintName("FK_DoanhThu_KhachHangMucTieu");

                    b.HasOne("CRM.Entities.LinhVucNgheNghiep", "LinhVucNgheNghiep")
                        .WithMany("KhachHangMucTieus")
                        .HasForeignKey("MaLinhVuc")
                        .HasConstraintName("FK_LinhVuc_KhachHangMucTieu");

                    b.HasOne("CRM.Entities.LoaiHinhNgheNghiep", "LoaiHinhNgheNghiep")
                        .WithMany("KhachHangMucTieus")
                        .HasForeignKey("MaLoaiHinhNgheNghiep")
                        .HasConstraintName("FK_LoaiHinhNgheNghiep_KhachHangMucTieu");

                    b.HasOne("CRM.Entities.LoaiTiemNang", "LoaiTiemNang")
                        .WithMany("KhachHangMucTieus")
                        .HasForeignKey("MaLoaiTiemNang")
                        .HasConstraintName("FK_LoaiTiemNang_KhachHangMucTieu");

                    b.HasOne("CRM.Entities.NganhNghe", "NganhNghe")
                        .WithMany("KhachHangMucTieus")
                        .HasForeignKey("MaNganhNghe")
                        .HasConstraintName("FK_NganhNghe_KhachHangMucTieu");

                    b.HasOne("CRM.Entities.NguonGocKhachHang", "NguonGocKhachHang")
                        .WithMany("KhachHangMucTieus")
                        .HasForeignKey("MaNguonGocKhachHang")
                        .HasConstraintName("FK_NguonGocKhachHang_KhachHangMucTieu");

                    b.HasOne("CRM.Entities.PhongBanKhachHang", "PhongBanKhachHang")
                        .WithMany("KhachHangMucTieus")
                        .HasForeignKey("MaPhongbanKhachHang")
                        .HasConstraintName("FK_PhongBanKhachhang_KhachHangMucTieu");

                    b.HasOne("CRM.Entities.Nguoidung", "Nguoidung")
                        .WithMany("KhachHangMucTieus")
                        .HasForeignKey("NguoiDungId")
                        .HasConstraintName("FK_NguoiDung_KhachHangMucTieu");

                    b.HasOne("CRM.Entities.PhongBan", "PhongBan")
                        .WithMany("KhachHangMucTieus")
                        .HasForeignKey("PhongBanId")
                        .HasConstraintName("FK_PhongBan_KhachHangMucTieu");

                    b.Navigation("DoanhThu");

                    b.Navigation("LinhVucNgheNghiep");

                    b.Navigation("LoaiHinhNgheNghiep");

                    b.Navigation("LoaiTiemNang");

                    b.Navigation("NganhNghe");

                    b.Navigation("Nguoidung");

                    b.Navigation("NguonGocKhachHang");

                    b.Navigation("PhongBan");

                    b.Navigation("PhongBanKhachHang");
                });

            modelBuilder.Entity("CRM.Entities.KhachHangTiemNang", b =>
                {
                    b.HasOne("CRM.Entities.DoanhThu", "DoanhThu")
                        .WithMany("KhachHangTiemNangs")
                        .HasForeignKey("MaDoanhThu")
                        .HasConstraintName("FK_DoanhThu_KhachHangTiemNang");

                    b.HasOne("CRM.Entities.LinhVucNgheNghiep", "LinhVucNgheNghiep")
                        .WithMany("KhachHangTiemNangs")
                        .HasForeignKey("MaLinhVuc")
                        .HasConstraintName("FK_LinhVuc_KhachHangTiemNang");

                    b.HasOne("CRM.Entities.LoaiHinhNgheNghiep", "LoaiHinhNgheNghiep")
                        .WithMany("KhachHangTiemNangs")
                        .HasForeignKey("MaLoaiHinhNgheNghiep")
                        .HasConstraintName("FK_LoaiHinhNgheNghiep_KhachHangTiemNang");

                    b.HasOne("CRM.Entities.LoaiTiemNang", "LoaiTiemNang")
                        .WithMany("KhachHangTiemNangs")
                        .HasForeignKey("MaLoaiTiemNang")
                        .HasConstraintName("FK_LoaiTiemNang_KhachHangTiemNang");

                    b.HasOne("CRM.Entities.NganhNghe", "NganhNghe")
                        .WithMany("KhachHangTiemNangs")
                        .HasForeignKey("MaNganhNghe")
                        .HasConstraintName("FK_NganhNghe_KhachHangTiemNang");

                    b.HasOne("CRM.Entities.NguonGocKhachHang", "NguonGocKhachHang")
                        .WithMany("KhachHangTiemNangs")
                        .HasForeignKey("MaNguonGocKhachHang")
                        .HasConstraintName("FK_NguonGocKhachHang_KhachHangTiemNang");

                    b.HasOne("CRM.Entities.PhongBanKhachHang", "PhongBanKhachHang")
                        .WithMany("KhachHangTiemNangs")
                        .HasForeignKey("MaPhongbanKhachHang")
                        .HasConstraintName("FK_PhongBanKhachhang_KhachHangTiemNang");

                    b.HasOne("CRM.Entities.Nguoidung", "Nguoidung")
                        .WithMany("KhachHangTiemNangs")
                        .HasForeignKey("NguoiDungId")
                        .HasConstraintName("FK_NguoiDung_KhachHangTiemNang");

                    b.HasOne("CRM.Entities.PhongBan", "PhongBan")
                        .WithMany("KhachHangTiemNangs")
                        .HasForeignKey("PhongBanId")
                        .HasConstraintName("FK_PhongBan_KhachHangTiemNang");

                    b.Navigation("DoanhThu");

                    b.Navigation("LinhVucNgheNghiep");

                    b.Navigation("LoaiHinhNgheNghiep");

                    b.Navigation("LoaiTiemNang");

                    b.Navigation("NganhNghe");

                    b.Navigation("Nguoidung");

                    b.Navigation("NguonGocKhachHang");

                    b.Navigation("PhongBan");

                    b.Navigation("PhongBanKhachHang");
                });

            modelBuilder.Entity("CRM.Entities.LichHen", b =>
                {
                    b.HasOne("CRM.Entities.CoHoi", "CoHoi")
                        .WithMany("LichHens")
                        .HasForeignKey("CoHoiId")
                        .HasConstraintName("FK_CoHoi_LichHen");

                    b.HasOne("CRM.Entities.KhachHangMucTieu", "KhachHangMucTieu")
                        .WithMany("LichHens")
                        .HasForeignKey("KhachHangMucTieuId")
                        .HasConstraintName("FK_KHMucTieu_LichHen");

                    b.HasOne("CRM.Entities.KhachHangTiemNang", "KhachHangTiemNang")
                        .WithMany("LichHens")
                        .HasForeignKey("KhachHangTiemNangId")
                        .HasConstraintName("FK_KhachHangTiemNang_LichHen");

                    b.HasOne("CRM.Entities.Nguoidung", "Nguoidung")
                        .WithMany("LichHens")
                        .HasForeignKey("NguoiDungId")
                        .HasConstraintName("FK_NguoiDung_LichHen");

                    b.HasOne("CRM.Entities.PhongBan", "PhongBan")
                        .WithMany("LichHens")
                        .HasForeignKey("PhongBanId")
                        .HasConstraintName("FK_PhongBan_LichHen");

                    b.HasOne("CRM.Entities.TrangThaiThucHien", "TrangThaiThucHien")
                        .WithMany("LichHens")
                        .HasForeignKey("TrangThaiThucHienId")
                        .HasConstraintName("FK_TrangThaiThucHien_LichHen");

                    b.Navigation("CoHoi");

                    b.Navigation("KhachHangMucTieu");

                    b.Navigation("KhachHangTiemNang");

                    b.Navigation("Nguoidung");

                    b.Navigation("PhongBan");

                    b.Navigation("TrangThaiThucHien");
                });

            modelBuilder.Entity("CRM.Entities.LienHe", b =>
                {
                    b.HasOne("CRM.Entities.Nguoidung", "Nguoidung")
                        .WithMany("LienHes")
                        .HasForeignKey("NguoiDungId")
                        .HasConstraintName("FK_NguoiDung_LienHe");

                    b.HasOne("CRM.Entities.PhongBan", "PhongBan")
                        .WithMany("LienHes")
                        .HasForeignKey("PhongBanId")
                        .HasConstraintName("FK_PhongBan_PhongBan");

                    b.Navigation("Nguoidung");

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("CRM.Entities.LoaiHangHoa", b =>
                {
                    b.HasOne("CRM.Entities.LoaiHangHoa", null)
                        .WithMany("LoaiHangHoas")
                        .HasForeignKey("LoaiHangHoaId");
                });

            modelBuilder.Entity("CRM.Entities.MenuRole", b =>
                {
                    b.HasOne("CRM.Entities.ChucVu", "ChucVu")
                        .WithMany("MenuRole")
                        .HasForeignKey("GroupId")
                        .IsRequired()
                        .HasConstraintName("FK_Menu_Role_ChucVu");

                    b.HasOne("CRM.Entities.Menu", "Menu")
                        .WithMany("MenuRoles")
                        .HasForeignKey("MenuId")
                        .IsRequired()
                        .HasConstraintName("FK_Menu_Role_Menu");

                    b.Navigation("ChucVu");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("CRM.Entities.NganhNghe", b =>
                {
                    b.HasOne("CRM.Entities.LinhVucNgheNghiep", "LinhVucNgheNghiep")
                        .WithMany("NganhNghes")
                        .HasForeignKey("MaLinhVucNgheNghiep")
                        .IsRequired()
                        .HasConstraintName("FK_NganhNghe_LinhVucNgheNghiep");

                    b.Navigation("LinhVucNgheNghiep");
                });

            modelBuilder.Entity("CRM.Entities.Nguoidung", b =>
                {
                    b.HasOne("CRM.Entities.ChucVu", "ChucVu")
                        .WithMany("Nguoidung")
                        .HasForeignKey("MaChucVu")
                        .HasConstraintName("FK_ChucVu_NguoiDung");

                    b.HasOne("CRM.Entities.PhongBan", "PhongBan")
                        .WithMany("Nguoidung")
                        .HasForeignKey("MaPhongBan")
                        .HasConstraintName("FK_PhongBan_NguoiDung");

                    b.HasOne("CRM.Entities.TinhTrang", "TinhTrang")
                        .WithMany("Nguoidung")
                        .HasForeignKey("MaTinhTrang")
                        .HasConstraintName("FK_TinhTrang_NguoiDung");

                    b.Navigation("ChucVu");

                    b.Navigation("PhongBan");

                    b.Navigation("TinhTrang");
                });

            modelBuilder.Entity("CRM.Entities.NhiemVu", b =>
                {
                    b.HasOne("CRM.Entities.CoHoi", "CoHoi")
                        .WithMany("NhiemVus")
                        .HasForeignKey("CoHoiId")
                        .HasConstraintName("FK_CoHoi_NhiemVu");

                    b.HasOne("CRM.Entities.KhachHangMucTieu", "KhachHangMucTieu")
                        .WithMany("NhiemVus")
                        .HasForeignKey("KhachHangMucTieuId")
                        .HasConstraintName("FK_KhachHangMucTieu_NhiemVu");

                    b.HasOne("CRM.Entities.KhachHangTiemNang", "KhachHangTiemNang")
                        .WithMany("NhiemVus")
                        .HasForeignKey("KhachHangTiemNangId")
                        .HasConstraintName("FK_KhachHangTiemNang_NhiemVu");

                    b.HasOne("CRM.Entities.MucDoUuTien", "MucDoUuTien")
                        .WithMany("NhiemVus")
                        .HasForeignKey("MucDoUuTienId")
                        .HasConstraintName("FK_MucDoUuTien_NhiemVu");

                    b.HasOne("CRM.Entities.Nguoidung", "Nguoidung")
                        .WithMany("NhiemVus")
                        .HasForeignKey("NguoiDungId")
                        .HasConstraintName("FK_NguoiDung_NhiemVu");

                    b.HasOne("CRM.Entities.PhongBan", "PhongBan")
                        .WithMany("NhiemVus")
                        .HasForeignKey("PhongBanId")
                        .HasConstraintName("FK_PhongBan_NhiemVu");

                    b.HasOne("CRM.Entities.TrangThaiThucHien", "TrangThaiThucHien")
                        .WithMany("NhiemVus")
                        .HasForeignKey("TrangThaiThucHienId")
                        .HasConstraintName("FK_TrangThaiThucHien_NhiemVu");

                    b.Navigation("CoHoi");

                    b.Navigation("KhachHangMucTieu");

                    b.Navigation("KhachHangTiemNang");

                    b.Navigation("MucDoUuTien");

                    b.Navigation("Nguoidung");

                    b.Navigation("PhongBan");

                    b.Navigation("TrangThaiThucHien");
                });

            modelBuilder.Entity("CRM.Entities.ChucVu", b =>
                {
                    b.Navigation("MenuRole");

                    b.Navigation("Nguoidung");
                });

            modelBuilder.Entity("CRM.Entities.CoHoi", b =>
                {
                    b.Navigation("BaoGias");

                    b.Navigation("ChiTietKetQua");

                    b.Navigation("CuocGois");

                    b.Navigation("LichHens");

                    b.Navigation("NhiemVus");
                });

            modelBuilder.Entity("CRM.Entities.DoanhThu", b =>
                {
                    b.Navigation("KhachHangMucTieus");

                    b.Navigation("KhachHangTiemNangs");
                });

            modelBuilder.Entity("CRM.Entities.DonViTinh", b =>
                {
                    b.Navigation("HangHoas");
                });

            modelBuilder.Entity("CRM.Entities.GiaiDoanBanHang", b =>
                {
                    b.Navigation("ChiTietKetQuas");

                    b.Navigation("CoHois");
                });

            modelBuilder.Entity("CRM.Entities.HangHoa", b =>
                {
                    b.Navigation("HangHoaQuanTams");
                });

            modelBuilder.Entity("CRM.Entities.KetQuaCuocGoi", b =>
                {
                    b.Navigation("CuocGois");
                });

            modelBuilder.Entity("CRM.Entities.KhachHangMucTieu", b =>
                {
                    b.Navigation("BaoGias");

                    b.Navigation("CoHois");

                    b.Navigation("CuocGois");

                    b.Navigation("DonHangs");

                    b.Navigation("EmailDaGuis");

                    b.Navigation("LichHens");

                    b.Navigation("NhiemVus");
                });

            modelBuilder.Entity("CRM.Entities.KhachHangTiemNang", b =>
                {
                    b.Navigation("CuocGois");

                    b.Navigation("EmailDaGuis");

                    b.Navigation("LichHens");

                    b.Navigation("NhiemVus");
                });

            modelBuilder.Entity("CRM.Entities.LienHe", b =>
                {
                    b.Navigation("CoHois");

                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("CRM.Entities.LinhVucNgheNghiep", b =>
                {
                    b.Navigation("KhachHangMucTieus");

                    b.Navigation("KhachHangTiemNangs");

                    b.Navigation("NganhNghes");
                });

            modelBuilder.Entity("CRM.Entities.LoaiCoHoi", b =>
                {
                    b.Navigation("CoHois");
                });

            modelBuilder.Entity("CRM.Entities.LoaiCuocGoi", b =>
                {
                    b.Navigation("CuocGois");
                });

            modelBuilder.Entity("CRM.Entities.LoaiDonHang", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("CRM.Entities.LoaiDuBao", b =>
                {
                    b.Navigation("GiaiDoanBanHangs");
                });

            modelBuilder.Entity("CRM.Entities.LoaiHangHoa", b =>
                {
                    b.Navigation("CoHois");

                    b.Navigation("HangHoas");

                    b.Navigation("LoaiHangHoas");
                });

            modelBuilder.Entity("CRM.Entities.LoaiHinhNgheNghiep", b =>
                {
                    b.Navigation("KhachHangMucTieus");

                    b.Navigation("KhachHangTiemNangs");
                });

            modelBuilder.Entity("CRM.Entities.LoaiTiemNang", b =>
                {
                    b.Navigation("KhachHangMucTieus");

                    b.Navigation("KhachHangTiemNangs");
                });

            modelBuilder.Entity("CRM.Entities.LyDo", b =>
                {
                    b.Navigation("ChiTietKetQuas");
                });

            modelBuilder.Entity("CRM.Entities.Menu", b =>
                {
                    b.Navigation("MenuRoles");
                });

            modelBuilder.Entity("CRM.Entities.MucDoUuTien", b =>
                {
                    b.Navigation("NhiemVus");
                });

            modelBuilder.Entity("CRM.Entities.NganhNghe", b =>
                {
                    b.Navigation("KhachHangMucTieus");

                    b.Navigation("KhachHangTiemNangs");
                });

            modelBuilder.Entity("CRM.Entities.Nguoidung", b =>
                {
                    b.Navigation("BaoGias");

                    b.Navigation("CoHois");

                    b.Navigation("CuocGois");

                    b.Navigation("DonHangs");

                    b.Navigation("EmailDaGuis");

                    b.Navigation("KhachHangMucTieus");

                    b.Navigation("KhachHangTiemNangs");

                    b.Navigation("LichHens");

                    b.Navigation("LienHes");

                    b.Navigation("NhiemVus");
                });

            modelBuilder.Entity("CRM.Entities.NguonGocKhachHang", b =>
                {
                    b.Navigation("CoHois");

                    b.Navigation("KhachHangMucTieus");

                    b.Navigation("KhachHangTiemNangs");
                });

            modelBuilder.Entity("CRM.Entities.PhanLoaiDuBao", b =>
                {
                    b.Navigation("GiaiDoanBanHangs");
                });

            modelBuilder.Entity("CRM.Entities.PhongBan", b =>
                {
                    b.Navigation("BaoGias");

                    b.Navigation("CoHois");

                    b.Navigation("CuocGois");

                    b.Navigation("DonHangs");

                    b.Navigation("EmailDaGuis");

                    b.Navigation("KhachHangMucTieus");

                    b.Navigation("KhachHangTiemNangs");

                    b.Navigation("LichHens");

                    b.Navigation("LienHes");

                    b.Navigation("Nguoidung");

                    b.Navigation("NhiemVus");
                });

            modelBuilder.Entity("CRM.Entities.PhongBanKhachHang", b =>
                {
                    b.Navigation("KhachHangMucTieus");

                    b.Navigation("KhachHangTiemNangs");
                });

            modelBuilder.Entity("CRM.Entities.TinhTrang", b =>
                {
                    b.Navigation("Nguoidung");
                });

            modelBuilder.Entity("CRM.Entities.TinhTrangBaoGia", b =>
                {
                    b.Navigation("BaoGias");
                });

            modelBuilder.Entity("CRM.Entities.TinhTrangDonHang", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("CRM.Entities.TinhTrangGhiDoanhSo", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("CRM.Entities.TrangThaiThucHien", b =>
                {
                    b.Navigation("LichHens");

                    b.Navigation("NhiemVus");
                });
#pragma warning restore 612, 618
        }
    }
}
